# Generated by Django 5.2.4 on 2026-05-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название проекта')),
                ('description', models.TextField(verbose_name='описание проекта')),
                ('created_at', models.DateTimeField(verbose_name='дата создания проекта')),
                ('github_url', models.URLField(blank=True, verbose_name='ссылка на Github')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6, verbose_name='статус проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
